language: php

php:
  - 7.1

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit tests --bootstrap tests/bootstrap.php --configuration phpunit.xml.dist --coverage-clover clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml