<?php

namespace Nip\Tests\Unit\Router\Parsers;

use Nip\Router\Parser\AbstractParser;

/**
 * Test class for Nip_Route_Abstract.
 * Generated by PHPUnit on 2010-11-17 at 15:16:44.
 */
class AbstractTest extends \Codeception\TestCase\Test
{
    /**
     * @var AbstractParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('AbstractParser');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

//    public function testSetMap()
//    {
//        $map = 'module/test';
//		$this->object->setMap($map);
//		static::assertEquals($map, $this->object->getMap());
//		static::assertEquals(2, count($this->object->getParts()));
//    }
//
//    public function testAssemble()
//    {
//        $params = array(
//            'url' => 'lorem',
//            'name' => 'ipsum',
//            'company' => 'dolo&rem',
//        );
//		static::assertEquals('?url=lorem&name=ipsum&company=dolo%26rem', $this->object->assemble($params));
//
//        $this->object->setMap(':url/:name');
//		static::assertEquals('lorem/ipsum?company=dolo%26rem', $this->object->assemble($params));
//    }
//
//    public function testStripEmptyParams()
//    {
//        $inputArray = array(
//            '1' => '',
//            '2' => '3',
//            '3' => array('123', '')
//        );
//        $outputArray = array(
//            '2' => '3',
//            '3' => array('123')
//        );
//
//		static::assertEquals($outputArray, $this->object->stripEmptyParams($inputArray));
//    }
}
