<?php

namespace Nip\Tests\Router\Parsers;

use Nip\Router\Parser\Regex;

/**
 * Test class for Nip_Route_Abstract.
 * Generated by PHPUnit on 2010-11-17 at 15:16:44.
 */
class Nip_Route_RegexTest extends  \Codeception\TestCase\Test
{

    /**
     * @var Regex
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->object = new Regex();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

//    public function testSetMap()
//    {
//        $this->object->setMap('shop/cart');
//		$this->assertEquals('shop/cart', $this->object->getRegex());
//
//        $this->object->setMap('shop/:cart');
//		$this->assertEquals('shop/:cart', $this->object->getRegex());
//
//        $this->object->setMap('shop/:cart');
//        $this->object->setParams(array('cart' => 'test'));
//		$this->assertEquals('shop/(test)', $this->object->getRegex());
//
//        $this->object->setMap('shop/:cart/:url');
//        $this->object->setParams(array('cart' => 'test', 'url' => '[a-z0-9-]+'));
//		$this->assertEquals('shop/(test)/([a-z0-9-]+)', $this->object->getRegex());
//
//    }
//
//    public function testAssemble()
//    {
//        $params = array(
//            'url' => 'lorem',
//            'name' => 'ipsum',
//            'company' => 'dolo&rem',
//        );
//		$this->assertEquals('?url=lorem&name=ipsum&company=dolo%26rem', $this->object->assemble($params));
//
//        $this->object->setMap('shop/:url');
//		$this->assertEquals('shop/lorem?name=ipsum&company=dolo%26rem', $this->object->assemble($params));
//    }
//
//    public function testMatch()
//    {
//        $this->object->setMap('shop/cart/:url');
//        $this->object->setParams(array('url' => '[a-z0-9-]+'));
//		$this->assertTrue($this->object->match('shop/cart/test'));
//		$this->assertTrue($this->object->match('shop/cart/test-teas'));
//		$this->assertTrue($this->object->match('shop/cart/test123-teas123'));
//		$this->assertFalse($this->object->match('shop/cart/test123_teas123'));
//    }

}