<?php

/**
 * Test class for Nip_Route_Abstract.
 * Generated by PHPUnit on 2010-11-17 at 15:16:44.
 */
class Nip_Route_DynamicTest extends  \Codeception\TestCase\Test
{

    /**
     * @var Nip_Route_Abstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->object = new Nip_Route_Dynamic();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

//    public function testSetMap()
//    {
//        $map = 'shop/category_:url/:name';
//		$this->object->setMap($map);
//		$this->assertEquals($map, $this->object->getMap());
//		$this->assertEquals(3, count($this->object->getParts()));
//		$this->assertEquals(array('url', 'name'), $this->object->getVariables());
//    }
//
//    public function testGetVariableFromPart()
//    {
//		$this->assertEquals(array('url'), $this->object->getVariableFromPart(':url'));
//		$this->assertEquals(array('url'), $this->object->getVariableFromPart('category_:url'));
//		$this->assertEquals(array('category', 'url_shop'), $this->object->getVariableFromPart(':category:url_shop'));
//		$this->assertEquals(array('category_main', 'url_shop'), $this->object->getVariableFromPart(':category_main:url_shop'));
//		$this->assertEquals(array('category', 'url_product'), $this->object->getVariableFromPart(':category-:url_product'));
//		$this->assertEquals(array('category', 'url_product'), $this->object->getVariableFromPart(':category-:url_product-test'));
//		$this->assertEquals(array('category', 'url_product'), $this->object->getVariableFromPart('shop-:category-:url_product-test'));
//		$this->assertEquals(array('category_main', 'url_product'), $this->object->getVariableFromPart('shop-:category_main-:url_product-test'));
//    }
//
//
//    public function testAssemble()
//    {
//        $params = array(
//            'url' => 'lorem',
//            'name' => 'ipsum',
//            'company' => 'dolo&rem',
//        );
//		$this->assertEquals('?url=lorem&name=ipsum&company=dolo%26rem', $this->object->assemble($params));
//
//        $this->object->setMap('shop/category_:url/:name');
//		$this->assertEquals('shop/category_lorem/ipsum?company=dolo%26rem', $this->object->assemble($params));
//    }
//
//    public function testMatch()
//    {
//        $map = 'shop/category_:url/:name';
//		$this->object->setMap($map);
//		$this->assertFalse($this->object->match('shop/category_cast/'));
//		$this->assertTrue($this->object->match('shop/category_cars/honda'));
//    }

}